name: release
on: 
  release:
    types: [published]

jobs:
  update:
    name: build
    runs-on: macOS-latest
    steps:
      - name: ‚¨áÔ∏è Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: üèó swiftbuild
        run: |
          swift build -c release --arch arm64 --arch x86_64
          echo "BUILD_DIR=.build/apple/Products/Release/" >> $GITHUB_ENV
      - name: üì¶ Build archive
        run: |
          cd "${{ env.BUILD_DIR }}"
          REPOSITORY_NAME=$(jq --raw-output '.repository.name' $GITHUB_EVENT_PATH)
          ./$REPOSITORY_NAME appify
          ARCHIVE_NAME=$REPOSITORY_NAME.app.zip
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV
          zip -r $ARCHIVE_NAME $REPOSITORY_NAME.app
      - name: ‚¨ÜÔ∏è Upload to Release
        run: |
          cd "${{ env.BUILD_DIR }}"
          ARTIFACT=./${{ env.ARCHIVE_NAME }}
          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
          CONTENT_LENGTH_HEADER="Content-Length: $(stat -f%z "$ARTIFACT")"
          CONTENT_TYPE_HEADER="Content-Type: application/zip"
          RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          FILENAME=$(basename $ARTIFACT)
          UPLOAD_URL="https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$FILENAME"
          echo "$UPLOAD_URL"
          curl -sSL -XPOST \
            -H "$AUTH_HEADER" -H "$CONTENT_LENGTH_HEADER" -H "$CONTENT_TYPE_HEADER" \
            --upload-file "$ARTIFACT" "$UPLOAD_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
